### ISSUE TITLE
What's the difference with `nekotools boot`?

### ISSUE THREAD

**Issue by RealyUniqueName** [tong/nekoboot#1]
There is a built-in ability to create standalone executables with neko: 

```
$ nekotools --help
Neko Tools v1.0 - (c)2006-2013 Haxe Foundation
Usage : nekotools [options]
 Options :
  server  : start a neko web server
  boot <file.n> : build an standalone executable
```

Does this library provide any advantages over 'standard' way to create executables?

**Comment by tong** [comment]
It does the same but you can easily integrate it into your development pipeline, for example use it with macros.
